# Formação Cientista de Dados

Pandas

Prof. Fernando Amaral

In [98]:
import pandas as pd

In [99]:
# Carrega arquivo para dataframe Pandas
# dados = pd.read_csv(r'C:\Users\felip\Formação Cientista de Dados\7.Prática em Python\dados\Credit.csv')
dados = pd.read_csv('Credit.csv')
# Formato
dados.shape  # x linhas, y colunas

(1000, 21)

In [100]:
# Resumo estatístico de colunas numéricas
dados.describe()

,duration,credit_amount,installment_commitment,residence_since,age,existing_credits,num_dependents
count,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000
mean,20.903000,3271.258000,2.973000,2.845000,35.546000,1.407000,1.155000
std,12.058814,2822.736876,1.118715,1.103718,11.375469,0.577654,0.362086
min,4.000000,250.000000,1.000000,1.000000,19.000000,1.000000,1.000000
25%,12.000000,1365.500000,2.000000,2.000000,27.000000,1.000000,1.000000
50%,18.000000,2319.500000,3.000000,3.000000,33.000000,1.000000,1.000000
75%,24.000000,3972.250000,4.000000,4.000000,42.000000,2.000000,1.000000
max,72.000000,18424.000000,4.000000,4.000000,75.000000,4.000000,2.000000

In [101]:
# Primeiros registros
dados.head(5)

,checking_status,duration,credit_history,purpose,credit_amount,savings_status,employment,installment_commitment,personal_status,other_parties,...,property_magnitude,age,other_payment_plans,housing,existing_credits,job,num_dependents,own_telephone,foreign_worker,class
0,<0,6,'critical/other existing credit',radio/tv,1169,'no known savings',>=7,4,'male single',none,...,'real estate',67,none,own,2,skilled,1,yes,yes,good
1,0<=X<200,48,'existing paid',radio/tv,5951,<100,1<=X<4,2,'female div/dep/mar',none,...,'real estate',22,none,own,1,skilled,1,none,yes,bad
2,'no checking',12,'critical/other existing credit',education,2096,<100,4<=X<7,2,'male single',none,...,'real estate',49,none,own,1,'unskilled resident',2,none,yes,good
3,<0,42,'existing paid',furniture/equipment,7882,<100,4<=X<7,2,'male single',guarantor,...,'life insurance',45,none,'for free',1,skilled,2,none,yes,good
4,<0,24,'delayed previously','new car',4870,<100,1<=X<4,3,'male single',none,...,'no known property',53,none,'for free',2,skilled,2,none,yes,bad

In [102]:
# Últimos registros, com parâmetros
dados.tail(2)

,checking_status,duration,credit_history,purpose,credit_amount,savings_status,employment,installment_commitment,personal_status,other_parties,...,property_magnitude,age,other_payment_plans,housing,existing_credits,job,num_dependents,own_telephone,foreign_worker,class
998,<0,45,'existing paid',radio/tv,1845,<100,1<=X<4,4,'male single',none,...,'no known property',23,none,'for free',1,skilled,1,yes,yes,bad
999,0<=X<200,45,'critical/other existing credit','used car',4576,100<=X<500,unemployed,3,'male single',none,...,car,27,none,own,1,skilled,1,none,yes,good

In [103]:
# Filtrar por nome da coluna
dados[[' duration']]

      duration
0            6
1           48
2           12
3           42
4           24
..         ...
995         12
996         30
997         12
998         45
999         45

[1000 rows x 1 columns]

In [104]:
# Filtrar linhas por índice
dados.loc[1:3]

,checking_status,duration,credit_history,purpose,credit_amount,savings_status,employment,installment_commitment,personal_status,other_parties,...,property_magnitude,age,other_payment_plans,housing,existing_credits,job,num_dependents,own_telephone,foreign_worker,class
1,0<=X<200,48,'existing paid',radio/tv,5951,<100,1<=X<4,2,'female div/dep/mar',none,...,'real estate',22,none,own,1,skilled,1,none,yes,bad
2,'no checking',12,'critical/other existing credit',education,2096,<100,4<=X<7,2,'male single',none,...,'real estate',49,none,own,1,'unskilled resident',2,none,yes,good
3,<0,42,'existing paid',furniture/equipment,7882,<100,4<=X<7,2,'male single',guarantor,...,'life insurance',45,none,'for free',1,skilled,2,none,yes,good

In [105]:
# Linhas
dados.loc[[1, 3, 10, 5, 7]]

,checking_status,duration,credit_history,purpose,credit_amount,savings_status,employment,installment_commitment,personal_status,other_parties,...,property_magnitude,age,other_payment_plans,housing,existing_credits,job,num_dependents,own_telephone,foreign_worker,class
1,0<=X<200,48,'existing paid',radio/tv,5951,<100,1<=X<4,2,'female div/dep/mar',none,...,'real estate',22,none,own,1,skilled,1,none,yes,bad
3,<0,42,'existing paid',furniture/equipment,7882,<100,4<=X<7,2,'male single',guarantor,...,'life insurance',45,none,'for free',1,skilled,2,none,yes,good
10,0<=X<200,12,'existing paid','new car',1295,<100,<1,3,'female div/dep/mar',none,...,car,25,none,rent,1,skilled,1,none,yes,bad
5,'no checking',36,'existing paid',education,9055,'no known savings',1<=X<4,2,'male single',none,...,'no known property',35,none,'for free',1,'unskilled resident',2,yes,yes,good
7,0<=X<200,36,'existing paid','used car',6948,<100,1<=X<4,2,'male single',none,...,car,35,none,rent,1,'high qualif/self emp/mgmt',1,yes,yes,good

In [106]:
# Filtro
dados.loc[dados[' purpose             '] == ' radio/tv            ']

,checking_status,duration,credit_history,purpose,credit_amount,savings_status,employment,installment_commitment,personal_status,other_parties,...,property_magnitude,age,other_payment_plans,housing,existing_credits,job,num_dependents,own_telephone,foreign_worker,class
0,<0,6,'critical/other existing credit',radio/tv,1169,'no known savings',>=7,4,'male single',none,...,'real estate',67,none,own,2,skilled,1,yes,yes,good
1,0<=X<200,48,'existing paid',radio/tv,5951,<100,1<=X<4,2,'female div/dep/mar',none,...,'real estate',22,none,own,1,skilled,1,none,yes,bad
8,'no checking',12,'existing paid',radio/tv,3059,>=1000,4<=X<7,2,'male div/sep',none,...,'real estate',61,none,own,1,'unskilled resident',1,none,yes,good
12,0<=X<200,12,'existing paid',radio/tv,1567,<100,1<=X<4,1,'female div/dep/mar',none,...,car,22,none,own,1,skilled,1,yes,yes,good
15,<0,24,'existing paid',radio/tv,1282,100<=X<500,1<=X<4,4,'female div/dep/mar',none,...,car,32,none,own,1,'unskilled resident',1,none,yes,bad
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
989,0<=X<200,24,'critical/other existing credit',radio/tv,1743,<100,>=7,4,'male single',none,...,'life insurance',48,none,own,2,'unskilled resident',1,none,yes,good
991,'no checking',15,'all paid',radio/tv,1569,100<=X<500,>=7,4,'male single',none,...,car,34,bank,own,1,'unskilled resident',2,none,yes,good
992,<0,18,'existing paid',radio/tv,1936,'no known savings',4<=X<7,2,'male mar/wid',none,...,car,23,none,rent,2,'unskilled resident',1,none,yes,good
997,'no checking',12,'existing paid',radio/tv,804,<100,>=7,4,'male single',none,...,car,38,none,own,1,skilled,1,none,yes,good
998,<0,45,'existing paid',radio/tv,1845,<100,1<=X<4,4,'male single',none,...,'no known property',23,none,'for free',1,skilled,1,yes,yes,bad

In [107]:
# Outra condição
dados.loc[dados[' credit_amount'] > 15000]

,checking_status,duration,credit_history,purpose,credit_amount,savings_status,employment,installment_commitment,personal_status,other_parties,...,property_magnitude,age,other_payment_plans,housing,existing_credits,job,num_dependents,own_telephone,foreign_worker,class
95,0<=X<200,54,'no credits/all paid',business,15945,<100,<1,3,'male single',none,...,'no known property',58,none,rent,1,skilled,1,yes,yes,bad
637,'no checking',60,'delayed previously',radio/tv,15653,<100,4<=X<7,2,'male single',none,...,car,21,none,own,2,skilled,1,yes,yes,good
818,<0,36,'existing paid',other,15857,<100,unemployed,2,'male div/sep','co applicant',...,car,43,none,own,1,'high qualif/self emp/mgmt',1,none,yes,good
887,0<=X<200,48,'existing paid',business,15672,<100,1<=X<4,2,'male single',none,...,car,23,none,own,1,skilled,1,yes,yes,bad
915,0<=X<200,48,'no credits/all paid',other,18424,<100,1<=X<4,1,'female div/dep/mar',none,...,'life insurance',32,bank,own,1,'high qualif/self emp/mgmt',1,yes,no,bad

In [108]:
# Atribuímos resultado a variável, criando outro df
credito2 = dados.loc[dados[' credit_amount'] > 18000]
print(credito2)

     checking_status   duration   credit_history                    \
915  0<=X<200                48   'no credits/all paid'

      purpose                credit_amount   savings_status       employment  \
915   other                          18424   <100                 1<=X<4

      installment_commitment   personal_status        other_parties   ...  \
915                        1   'female div/dep/mar'   none            ...

      property_magnitude   age   other_payment_plans   housing     \
915   'life insurance'      32   bank                  own

     existing_credits   job                          num_dependents  \
915                 1   'high qualif/self emp/mgmt'               1

      own_telephone   foreign_worker  class
915   yes             no                bad

[1 rows x 21 columns]

In [109]:
# Definimos só algumas colunas
credito3 = dados[['checking_status', ' duration']].loc[dados[' credit_amount'] >  18000]
print(credito3)

     checking_status   duration
915  0<=X<200                48

In [110]:
# Series, única coluna;
# Pode ser criada a partir de listas, array do numpy ou coluna de data frame
s1 = pd.Series([2, 5, 3, 34, 54, 23, 1, 16])
print(s1)

0     2
1     5
2     3
3    34
4    54
5    23
6     1
7    16
dtype: int64

In [111]:
# Série a partir de um array do numpy
import numpy as np
array1 = np.array([2, 5, 3, 34, 54, 23, 1, 16])
print(array1, type(array1))
s2 = pd.Series(array1)
print(s2, type(s2))

[ 2  5  3 34 54 23  1 16] <class 'numpy.ndarray'>
0     2
1     5
2     3
3    34
4    54
5    23
6     1
7    16
dtype: int32 <class 'pandas.core.series.Series'>

In [112]:
# Series a partir de um dataframe
s3 = dados[' purpose             ']
print(s3, type(s3))

0       radio/tv
1       radio/tv
2       education
3       furniture/equipment
4       'new car'
               ...
995     furniture/equipment
996     'used car'
997     radio/tv
998     radio/tv
999     'used car'
Name:  purpose             , Length: 1000, dtype: object <class 'pandas.core.series.Series'>

In [113]:
# Note a diferença, temos um data frame
d4= dados[[' purpose             ']]
print(d4, type(d4))

      purpose
0     radio/tv
1     radio/tv
2     education
3     furniture/equipment
4     'new car'
..                     ...
995   furniture/equipment
996   'used car'
997   radio/tv
998   radio/tv
999   'used car'

[1000 rows x 1 columns] <class 'pandas.core.frame.DataFrame'>

In [114]:
# Renomear
dados.rename(columns={" duration":"duração", " purpose             ":"propósito"})

,checking_status,duração,credit_history,propósito,credit_amount,savings_status,employment,installment_commitment,personal_status,other_parties,...,property_magnitude,age,other_payment_plans,housing,existing_credits,job,num_dependents,own_telephone,foreign_worker,class
0,<0,6,'critical/other existing credit',radio/tv,1169,'no known savings',>=7,4,'male single',none,...,'real estate',67,none,own,2,skilled,1,yes,yes,good
1,0<=X<200,48,'existing paid',radio/tv,5951,<100,1<=X<4,2,'female div/dep/mar',none,...,'real estate',22,none,own,1,skilled,1,none,yes,bad
2,'no checking',12,'critical/other existing credit',education,2096,<100,4<=X<7,2,'male single',none,...,'real estate',49,none,own,1,'unskilled resident',2,none,yes,good
3,<0,42,'existing paid',furniture/equipment,7882,<100,4<=X<7,2,'male single',guarantor,...,'life insurance',45,none,'for free',1,skilled,2,none,yes,good
4,<0,24,'delayed previously','new car',4870,<100,1<=X<4,3,'male single',none,...,'no known property',53,none,'for free',2,skilled,2,none,yes,bad
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,'no checking',12,'existing paid',furniture/equipment,1736,<100,4<=X<7,3,'female div/dep/mar',none,...,'real estate',31,none,own,1,'unskilled resident',1,none,yes,good
996,<0,30,'existing paid','used car',3857,<100,1<=X<4,4,'male div/sep',none,...,'life insurance',40,none,own,1,'high qualif/self emp/mgmt',1,yes,yes,good
997,'no checking',12,'existing paid',radio/tv,804,<100,>=7,4,'male single',none,...,car,38,none,own,1,skilled,1,none,yes,good
998,<0,45,'existing paid',radio/tv,1845,<100,1<=X<4,4,'male single',none,...,'no known property',23,none,'for free',1,skilled,1,yes,yes,bad
999,0<=X<200,45,'critical/other existing credit','used car',4576,100<=X<500,unemployed,3,'male single',none,...,car,27,none,own,1,skilled,1,none,yes,good

In [115]:
# Porém a alteração não é persistida
dados.head(1)

,checking_status,duration,credit_history,purpose,credit_amount,savings_status,employment,installment_commitment,personal_status,other_parties,...,property_magnitude,age,other_payment_plans,housing,existing_credits,job,num_dependents,own_telephone,foreign_worker,class
0,<0,6,'critical/other existing credit',radio/tv,1169,'no known savings',>=7,4,'male single',none,...,'real estate',67,none,own,2,skilled,1,yes,yes,good

In [116]:
# Para persistir
dados.rename(columns={"duração":"duration", "propósito":"purpose"}, inplace=True)

In [117]:
dados.head(1)

,checking_status,duration,credit_history,purpose,credit_amount,savings_status,employment,installment_commitment,personal_status,other_parties,...,property_magnitude,age,other_payment_plans,housing,existing_credits,job,num_dependents,own_telephone,foreign_worker,class
0,<0,6,'critical/other existing credit',radio/tv,1169,'no known savings',>=7,4,'male single',none,...,'real estate',67,none,own,2,skilled,1,yes,yes,good

In [118]:
# Excluir coluna
dados.drop(' credit_history                  ',axis=1,inplace=True)
print(dados)

     checking_status   duration   purpose                credit_amount  \
0    <0                       6   radio/tv                        1169
1    0<=X<200                48   radio/tv                        5951
2    'no checking'           12   education                       2096
3    <0                      42   furniture/equipment             7882
4    <0                      24   'new car'                       4870
..               ...        ...                    ...             ...
995  'no checking'           12   furniture/equipment             1736
996  <0                      30   'used car'                      3857
997  'no checking'           12   radio/tv                         804
998  <0                      45   radio/tv                        1845
999  0<=X<200                45   'used car'                      4576

      savings_status       employment   installment_commitment  \
0     'no known savings'   >=7                               4
1     <100                 1<=X<4                            2
2     <100                 4<=X<7                            2
3     <100                 4<=X<7                            2
4     <100                 1<=X<4                            3
..                   ...          ...                      ...
995   <100                 4<=X<7                            3
996   <100                 1<=X<4                            4
997   <100                 >=7                               4
998   <100                 1<=X<4                            4
999   100<=X<500           unemployed                        3

      personal_status        other_parties    residence_since  \
0     'male single'          none                           4
1     'female div/dep/mar'   none                           2
2     'male single'          none                           3
3     'male single'          guarantor                      4
4     'male single'          none                           4
..                     ...              ...               ...
995   'female div/dep/mar'   none                           4
996   'male div/sep'         none                           4
997   'male single'          none                           4
998   'male single'          none                           4
999   'male single'          none                           4

      property_magnitude    age   other_payment_plans   housing     \
0     'real estate'          67   none                  own
1     'real estate'          22   none                  own
2     'real estate'          49   none                  own
3     'life insurance'       45   none                  'for free'
4     'no known property'    53   none                  'for free'
..                    ...   ...                   ...          ...
995   'real estate'          31   none                  own
996   'life insurance'       40   none                  own
997   car                    38   none                  own
998   'no known property'    23   none                  'for free'
999   car                    27   none                  own

      existing_credits   job                           num_dependents  \
0                    2   skilled                                    1
1                    1   skilled                                    1
2                    1   'unskilled resident'                       2
3                    1   skilled                                    2
4                    2   skilled                                    2
..                 ...                           ...              ...
995                  1   'unskilled resident'                       1
996                  1   'high qualif/self emp/mgmt'                1
997                  1   skilled                                    1
998                  1   skilled                                    1
999                  1   skilled                                    1

      own_telephone   foreign_worker  class
0     yes             yes              good
1     none            yes               bad
2     none            yes              good
3     none            yes              good
4     none            yes               bad
..              ...              ...    ...
995   none            yes              good
996   yes             yes              good
997   none            yes              good
998   yes             yes               bad
999   none            yes              good

[1000 rows x 20 columns]

In [119]:
dados.head(1)

,checking_status,duration,purpose,credit_amount,savings_status,employment,installment_commitment,personal_status,other_parties,residence_since,property_magnitude,age,other_payment_plans,housing,existing_credits,job,num_dependents,own_telephone,foreign_worker,class
0,<0,6,radio/tv,1169,'no known savings',>=7,4,'male single',none,4,'real estate',67,none,own,2,skilled,1,yes,yes,good

In [120]:
# Verificar dados nulos
dados.isnull()

,checking_status,duration,purpose,credit_amount,savings_status,employment,installment_commitment,personal_status,other_parties,residence_since,property_magnitude,age,other_payment_plans,housing,existing_credits,job,num_dependents,own_telephone,foreign_worker,class
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
996,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
997,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
998,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
999,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False

In [121]:
# Verificar dados nulos
dados.isnull().sum()

checking_status                 0
 duration                       0
 purpose                        0
 credit_amount                  0
 savings_status                 0
 employment                     0
 installment_commitment         0
 personal_status                0
 other_parties                  0
 residence_since                0
 property_magnitude             0
 age                            0
 other_payment_plans            0
 housing                        0
 existing_credits               0
 job                            0
 num_dependents                 0
 own_telephone                  0
 foreign_worker                 0
 class                          0
dtype: int64

In [122]:
# Retirar colunas com NaN
dados.dropna()

,checking_status,duration,purpose,credit_amount,savings_status,employment,installment_commitment,personal_status,other_parties,residence_since,property_magnitude,age,other_payment_plans,housing,existing_credits,job,num_dependents,own_telephone,foreign_worker,class
0,<0,6,radio/tv,1169,'no known savings',>=7,4,'male single',none,4,'real estate',67,none,own,2,skilled,1,yes,yes,good
1,0<=X<200,48,radio/tv,5951,<100,1<=X<4,2,'female div/dep/mar',none,2,'real estate',22,none,own,1,skilled,1,none,yes,bad
2,'no checking',12,education,2096,<100,4<=X<7,2,'male single',none,3,'real estate',49,none,own,1,'unskilled resident',2,none,yes,good
3,<0,42,furniture/equipment,7882,<100,4<=X<7,2,'male single',guarantor,4,'life insurance',45,none,'for free',1,skilled,2,none,yes,good
4,<0,24,'new car',4870,<100,1<=X<4,3,'male single',none,4,'no known property',53,none,'for free',2,skilled,2,none,yes,bad
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,'no checking',12,furniture/equipment,1736,<100,4<=X<7,3,'female div/dep/mar',none,4,'real estate',31,none,own,1,'unskilled resident',1,none,yes,good
996,<0,30,'used car',3857,<100,1<=X<4,4,'male div/sep',none,4,'life insurance',40,none,own,1,'high qualif/self emp/mgmt',1,yes,yes,good
997,'no checking',12,radio/tv,804,<100,>=7,4,'male single',none,4,car,38,none,own,1,skilled,1,none,yes,good
998,<0,45,radio/tv,1845,<100,1<=X<4,4,'male single',none,4,'no known property',23,none,'for free',1,skilled,1,yes,yes,bad
999,0<=X<200,45,'used car',4576,100<=X<500,unemployed,3,'male single',none,4,car,27,none,own,1,skilled,1,none,yes,good

In [123]:
# Preencher dados faltantes
dados['duration'].fillna(0,inplace = True)

KeyError: 'duration'

In [ ]:
# iloc
dados.iloc[:3 , :5]

In [ ]:
dados.iloc[[0, 1, 2, 3, 7], :5]